extends Node

const COMBAT_STATE_NAMES: Dictionary = {
	"EnemySelection" : "EnemySelection",
	"Preparation" : "Preparation",
	"PlayerAttack" : "PlayerAttack",
	"EnemyTurn" : "EnemyTurn",
	"Victory" : "Victory",
	"Defeat" : "Defeat"
}

const RARITY_ID: Dictionary = {
	"COMMON" : 1,
	"RARE" : 2,
	"EPIC" : 3,
	"LEGENDARY" : 4,
}

const ATTACK_TYPE: Dictionary = {
	"SINGLE" : 1,
	"HALF" : 2,
	"ALL" : 3,
}

enum BALL_RARITY {
	RARITY_COMMON = 1,
	RARITY_UNCOMMON = 2,
	RARITY_RARE = 3,
	RARITY_EPIC = 4,
	RARITY_LEGENDARY = 5,
}

enum BALL_TARGET {
	TARGET_SINGLE = 1,
	TARGET_HALF = 2,
	TARGET_ALL = 3,
}

enum BALL_ATTACK_PROFILE {
	PROFILE_UNI_TARGET,
	PROFILE_MULTI_TARGET,
	PROFILE_CLEAVE,
	PROFILE_DOT,
	PROFILE_SUPPORT,
	PROFILE_UTILITY,
	PROFILE_CONTROL,
	PROFILE_ECONOMY,
	PROFILE_JACKPOT,
	PROFILE_RANDOM,
	PROFILE_COPY,
	PROFILE_COMBO,
	PROFILE_EXECUTE,
	PROFILE_FINISHER,
	PROFILE_SYNERGY,
}

enum BALL_CATEGORY {
	CATEGORY_DAMAGE,
	CATEGORY_SUPPORT,
	CATEGORY_SUSTAIN,
	CATEGORY_DEFENSE,
	CATEGORY_ECONOMY,
	CATEGORY_CONTROL,
	CATEGORY_DOT,
	CATEGORY_AOE,
	CATEGORY_MULTIPLIER,
	CATEGORY_COPY,
	CATEGORY_JACKPOT,
	CATEGORY_RISK_REWARD,
	CATEGORY_DEBUFF,
	CATEGORY_EXECUTE,
	CATEGORY_FINISHER,
	CATEGORY_SYNERGY,
	CATEGORY_RANDOM,
	CATEGORY_CHAIN,
	CATEGORY_PIERCE,
	CATEGORY_BURST,
}

enum PASSIVE_ITEM_RARITY {
	RARITY_COMMON = 1,
	RARITY_UNCOMMON = 2,
	RARITY_RARE = 3,
	RARITY_EPIC = 4,
	RARITY_LEGENDARY = 5,
}

enum PASSIVE_ITEM_TRIGGER {
	TRIGGER_COMBAT_START,
	TRIGGER_PRE_RESOLVE,
	TRIGGER_REROLL,
	TRIGGER_BET_RESOLVED,
	TRIGGER_POST_RESOLVED,
	TRIGGER_COMBAT_END,
	TRIGGER_COMBAT_KILL,
	TRIGGER_ENEMY_KILLED,
	TRIGGER_LOADOUT,
	TRIGGER_REWARD_GENERATED,
	TRIGGER_SHOP_GENERATED,
	TRIGGER_CHEST_OPENED,
	TRIGGER_EVENT_REWARD_GENERATED,
	TRIGGER_STATUS_TICK,
}

enum PASSIVE_ITEM_STATUS {
	STATUS_CONCEPT,
	STATUS_IN_GAME,
}

const BALL_RARITY_BY_NAME: Dictionary = {
	"common": BALL_RARITY.RARITY_COMMON,
	"uncommon": BALL_RARITY.RARITY_UNCOMMON,
	"rare": BALL_RARITY.RARITY_RARE,
	"epic": BALL_RARITY.RARITY_EPIC,
	"legendary": BALL_RARITY.RARITY_LEGENDARY,
}

const BALL_CATEGORY_BY_NAME: Dictionary = {
	"damage": BALL_CATEGORY.CATEGORY_DAMAGE,
	"base_damage": BALL_CATEGORY.CATEGORY_DAMAGE,
	"support": BALL_CATEGORY.CATEGORY_SUPPORT,
	"sustain": BALL_CATEGORY.CATEGORY_SUSTAIN,
	"defense": BALL_CATEGORY.CATEGORY_DEFENSE,
	"economy": BALL_CATEGORY.CATEGORY_ECONOMY,
	"control": BALL_CATEGORY.CATEGORY_CONTROL,
	"roulette_control": BALL_CATEGORY.CATEGORY_CONTROL,
	"dot": BALL_CATEGORY.CATEGORY_DOT,
	"aoe": BALL_CATEGORY.CATEGORY_AOE,
	"final_multiplier": BALL_CATEGORY.CATEGORY_MULTIPLIER,
	"copy": BALL_CATEGORY.CATEGORY_COPY,
	"combo_copy": BALL_CATEGORY.CATEGORY_COPY,
	"jackpot": BALL_CATEGORY.CATEGORY_JACKPOT,
	"jackpot_aoe": BALL_CATEGORY.CATEGORY_JACKPOT,
	"risk_reward": BALL_CATEGORY.CATEGORY_RISK_REWARD,
	"debuff": BALL_CATEGORY.CATEGORY_DEBUFF,
	"execute": BALL_CATEGORY.CATEGORY_EXECUTE,
	"finisher": BALL_CATEGORY.CATEGORY_FINISHER,
	"gold_synergy": BALL_CATEGORY.CATEGORY_SYNERGY,
	"prime_condition": BALL_CATEGORY.CATEGORY_SYNERGY,
	"color_condition": BALL_CATEGORY.CATEGORY_SYNERGY,
	"convergence": BALL_CATEGORY.CATEGORY_SYNERGY,
	"random": BALL_CATEGORY.CATEGORY_RANDOM,
	"chain": BALL_CATEGORY.CATEGORY_CHAIN,
	"pierce": BALL_CATEGORY.CATEGORY_PIERCE,
	"shield_conversion": BALL_CATEGORY.CATEGORY_BURST,
}

const PASSIVE_ITEM_RARITY_BY_NAME: Dictionary = {
	"common": PASSIVE_ITEM_RARITY.RARITY_COMMON,
	"uncommon": PASSIVE_ITEM_RARITY.RARITY_UNCOMMON,
	"rare": PASSIVE_ITEM_RARITY.RARITY_RARE,
	"epic": PASSIVE_ITEM_RARITY.RARITY_EPIC,
	"legendary": PASSIVE_ITEM_RARITY.RARITY_LEGENDARY,
}

const PASSIVE_ITEM_TRIGGER_BY_NAME: Dictionary = {
	"combat_start": PASSIVE_ITEM_TRIGGER.TRIGGER_COMBAT_START,
	"pre_resolve": PASSIVE_ITEM_TRIGGER.TRIGGER_PRE_RESOLVE,
	"reroll": PASSIVE_ITEM_TRIGGER.TRIGGER_REROLL,
	"bet_resolved": PASSIVE_ITEM_TRIGGER.TRIGGER_BET_RESOLVED,
	"post_resolved": PASSIVE_ITEM_TRIGGER.TRIGGER_POST_RESOLVED,
	"combat_end": PASSIVE_ITEM_TRIGGER.TRIGGER_COMBAT_END,
	"combat_kill": PASSIVE_ITEM_TRIGGER.TRIGGER_COMBAT_KILL,
	"enemy_killed": PASSIVE_ITEM_TRIGGER.TRIGGER_ENEMY_KILLED,
	"loadout": PASSIVE_ITEM_TRIGGER.TRIGGER_LOADOUT,
	"reward_generated": PASSIVE_ITEM_TRIGGER.TRIGGER_REWARD_GENERATED,
	"shop_generated": PASSIVE_ITEM_TRIGGER.TRIGGER_SHOP_GENERATED,
	"chest_opened": PASSIVE_ITEM_TRIGGER.TRIGGER_CHEST_OPENED,
	"event_reward_generated": PASSIVE_ITEM_TRIGGER.TRIGGER_EVENT_REWARD_GENERATED,
	"status_tick": PASSIVE_ITEM_TRIGGER.TRIGGER_STATUS_TICK,
}

const BALL_ATTACK_PROFILE_BY_NAME: Dictionary = {
	"uni-target": BALL_ATTACK_PROFILE.PROFILE_UNI_TARGET,
	"single": BALL_ATTACK_PROFILE.PROFILE_UNI_TARGET,
	"multi-target": BALL_ATTACK_PROFILE.PROFILE_MULTI_TARGET,
	"multi_target": BALL_ATTACK_PROFILE.PROFILE_MULTI_TARGET,
	"cleave": BALL_ATTACK_PROFILE.PROFILE_CLEAVE,
	"dot": BALL_ATTACK_PROFILE.PROFILE_DOT,
	"support": BALL_ATTACK_PROFILE.PROFILE_SUPPORT,
	"utility": BALL_ATTACK_PROFILE.PROFILE_UTILITY,
	"control": BALL_ATTACK_PROFILE.PROFILE_CONTROL,
	"economy": BALL_ATTACK_PROFILE.PROFILE_ECONOMY,
	"jackpot": BALL_ATTACK_PROFILE.PROFILE_JACKPOT,
	"random": BALL_ATTACK_PROFILE.PROFILE_RANDOM,
	"copy": BALL_ATTACK_PROFILE.PROFILE_COPY,
	"combo": BALL_ATTACK_PROFILE.PROFILE_COMBO,
	"execute": BALL_ATTACK_PROFILE.PROFILE_EXECUTE,
	"finisher": BALL_ATTACK_PROFILE.PROFILE_FINISHER,
	"synergy": BALL_ATTACK_PROFILE.PROFILE_SYNERGY,
}

const BOARD_TAG: Dictionary = {
	"GOLDEN": "board_tag_golden",
	"BOTH_COLORS": "board_tag_both_colors",
}

const BALL_EFFECT_FLAG: Dictionary = {
	"BOUNCE_HITS": "bounce_ball_hits",
	"MIRROR_COPY_POWER": "mirror_ball_copy_power",
	"POISON_DAMAGE": "poison_ball_damage",
	"POISON_TURNS": "poison_ball_turns",
	"FIRE_SPLASH_PCT": "fire_ball_splash_pct",
	"MUTE_TURNS": "mute_ball_turns",
	"MUTE_ENEMY_DAMAGE_REDUCTION": "mute_ball_enemy_damage_reduction",
	"CRYSTAL_CORRECTION_RANGE": "crystal_ball_correction_range",
	"CURSE_VULNERABLE_PCT": "curse_ball_vulnerable_pct",
	"CURSE_VULNERABLE_TURNS": "curse_ball_vulnerable_turns",
	"STORM_CHAIN_TARGETS": "storm_ball_chain_targets",
	"RIG_CORRECTION_RANGE": "rig_ball_correction_range",
	"ECHO_REPEAT_POWER": "echo_ball_repeat_power",
	"VOID_IGNORE_SHIELD": "void_ball_ignore_shield",
	"GRAVE_EXECUTE_THRESHOLD": "grave_ball_execute_threshold",
	"COMBAT_ANY_TARGET_DEBUFFED": "combat_any_target_debuffed",
	"COMBAT_USED_BALL_TYPES": "combat_used_ball_types",
	"JACKPOT_AOE_DAMAGE": "jackpot_ball_aoe_damage",
	"FATE_ROLLS": "fate_ball_rolls",
	"CHRONO_REPEAT_COUNT": "chrono_ball_repeat_count",
	"CHRONO_REPEAT_POWER": "chrono_ball_repeat_power",
}

enum BOOK_PAGE {
	ROULETTE,
	CASE,
	MAP,
	NONE
}

#betfields colors
enum BET_FIELD_COLOR {
	GREEN,
	RED,
	BLACK,
}
enum BET_FIELD_PARITY {
	EVEN,
	ODD,
	NONE
}
enum BET_FIELD_HALF_TABLE {
	LESS_18,
	GREATER_19,
	NONE
}
enum BET_FIELD_COLUMN {
	COLUMN_1ST,
	COLUMN_2ND,
	COLUMN_3RD,
	NONE
}
enum BET_FIELD_ROW {
	ROW_1ST,
	ROW_2ND,
	ROW_3RD,
	NONE
}
#scene routes
const TEST_SCENE = "res://RouletteCombat.tscn"
const MAP_SCENE = "res://MapGeneration/map_scene.tscn"
